[features]
seeds = false
skip-lint = false
[programs.localnet]
hello_solana = "3XVtSTEXibQ1sEt2BM1VrrLyG1vKbtpwivZkhbUeR2Jk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/praky/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
